[general]
import = [
  "font.toml",
  "colors.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 8

[mouse]
hide_when_typing = true

[window.padding]
x = 0
y = 0
